### ISSUE TITLE
'Any' object has no attribute 'qname'

### ISSUE THREAD

**Issue by c-engelhardt-ecoservice** [mvantellingen/python-zeep#75]
I'm trying to send the following request:

```
...
client = zeep.Client('https://adi-uat.apmg-international.com/95/lookupdata.asmx?WSDL')
response = client.service.GetExamName(ATO_ID=ato_id, ATO_KEY=ato_key)
...

```

But get the following issue:

```
Traceback (most recent call last):
  File "soap_connection.py", line 161, in sync_soap_object
    response = client.service.GetExamName(ATO_ID=ato_id, ATO_KEY=ato_key)
  File "/usr/lib/python2.7/site-packages/zeep/client.py", line 24, in __call__
    self._proxy._client, self._op_name, args, kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 298, in send
    client, self.binding_options, operation, args, kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 99, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 134, in process_reply
    doc = operation.process_reply(doc)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 265, in process_reply
    return self.output.deserialize(node)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 205, in deserialize
    result.append(part.element.parse(elm, self.wsdl.schema))
  File "/usr/lib/python2.7/site-packages/zeep/xsd/elements.py", line 128, in parse
    return self.type.parse_xmlelement(value, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/types.py", line 255, in parse_xmlelement
    result = field.parse(element, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/elements.py", line 128, in parse
    return self.type.parse_xmlelement(value, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/types.py", line 242, in parse_xmlelement
    while field and field.qname != element.tag:
AttributeError: 'Any' object has no attribute 'qname'
```

I attached the request/response xml from SoapUI as example:
[example.zip](https://github.com/mvantellingen/python-zeep/files/313364/example.zip)

**Comment by mvantellingen** [comment]
See https://github.com/mvantellingen/python-zeep/commit/ea5112dc793a9b3d2cdfe96c02379b85771fe5f8

Needs some more work in the future. I think instead of returning the lxml element we should create a python datastructure

**Comment by mvantellingen** [comment]
Closing it for now

**Comment by c-engelhardt-ecoservice** [comment]
Thanks a lot!! A python datastructure will be awesome when it's done but the xml element will work for me for now.
Keep up the good work!

**Comment by mattpepin** [comment]
I'm getting this also in latest master. Should I open a new bug @mvantellingen ?

Using the following WSDL from the ONVIF spec: http://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl

```
Traceback (most recent call last):
  File "onvif-test.py", line 55, in <module>
    print(o.devicemgmt.GetServices(IncludeCapability=True))
  File "test/lib/python3.5/site-packages/zeep/client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "test/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 94, in send
    return self.process_reply(client, operation_obj, response)
  File "test/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 125, in process_reply
    return operation.process_reply(doc)
  File "test/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 249, in process_reply
    return self.output.deserialize(node)
  File "test/lib/python3.5/site-packages/zeep/wsdl/messages.py", line 208, in deserialize
    result.append(part.element.parse(elm, self.wsdl.types))
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 173, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 223, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 403, in parse_xmlelements
    item_subresult = element.parse_xmlelements(xmlelements, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 181, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 173, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 217, in parse_xmlelement
    value = attributes.get(attribute.qname.text)
AttributeError: 'Any' object has no attribute 'qname'
```

**Comment by mvantellingen** [comment]
Turns out it was missing proper support for anyAttribute's. Should be working in master

**Comment by mattpepin** [comment]
There's progress, but not quite there yet. Here's the new traceback:

```
Traceback (most recent call last):
  File "onvif-test.py", line 55, in <module>
    print(o.devicemgmt.GetServices(IncludeCapability=True))
  File "test/lib/python3.5/site-packages/zeep/client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "test/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 94, in send
    return self.process_reply(client, operation_obj, response)
  File "test/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 125, in process_reply
    return operation.process_reply(doc)
  File "test/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 249, in process_reply
    return self.output.deserialize(node)
  File "test/lib/python3.5/site-packages/zeep/wsdl/messages.py", line 208, in deserialize
    result.append(part.element.parse(elm, self.wsdl.types))
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 192, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 230, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 403, in parse_xmlelements
    item_subresult = element.parse_xmlelements(xmlelements, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 200, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 192, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 230, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 403, in parse_xmlelements
    item_subresult = element.parse_xmlelements(xmlelements, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 200, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 192, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 230, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 403, in parse_xmlelements
    item_subresult = element.parse_xmlelements(xmlelements, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 95, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 85, in parse
    return element_type.parse(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 192, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 230, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 403, in parse_xmlelements
    item_subresult = element.parse_xmlelements(xmlelements, schema, name)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 200, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 192, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 223, in parse_xmlelement
    init_kwargs[name] = attribute.parse(value)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 259, in parse
    return self.type.pythonvalue(value)
AttributeError: 'ListType' object has no attribute 'pythonvalue'
```

Thanks!

**Comment by mvantellingen** [comment]
See new commit. If that still gives issues I'll probably look at it in a few days again. Or if you could submit a PR that would be even better :-)

**Comment by mattpepin** [comment]
No problem ;). There's still an error but I'll try to fix it.

```
File "test/lib/python3.5/site-packages/zeep/xsd/builtins.py", line 396, in pythonvalue
    return long(value) if six.PY2 else int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
